server:
  port: 8761 # Puerto estándar mundial de Eureka

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false # Soy el servidor, no me registro
    fetch-registry: false       # No necesito buscar a otros
